### ISSUE TITLE
path_regulation issue: robots struggle to rotate of a big without taking a lot of space

### ISSUE THREAD

**Issue by jeanfrancoisburnier** [jeanfrancoisburnier/gr14#33]
If the next target is located behind the robot and the place to navigate is narrow, the robot cannot turn without hitting the walls. Currently using a first order filter on the speed command, what makes the reactivity kind of slow

**Comment by jeanfrancoisburnier** [comment]
Even when adding a delay between each target (~1.5s) the robot takes a lot a space to do a 180° rotation

**Comment by AThabuis** [comment]
done, it can now move also backwards
