### ISSUE TITLE
Path planning issue: Wrong goal id

### ISSUE THREAD

**Issue by jeanfrancoisburnier** [jeanfrancoisburnier/gr14#39]
Pour la target (0.25,1.25) le programme assigne comme goal l'id: 19. Donc le robot va dans la base jaune en haut à gauche plutôt que sur la target. (Ce problème se répète pour les goals se trouvant en haut de la map).

**Comment by jeanfrancoisburnier** [comment]
wrong ID assignation

**Comment by AThabuis** [comment]
Done
