### ISSUE TITLE
Finish calibration

### ISSUE THREAD

**Issue by jeanfrancoisburnier** [jeanfrancoisburnier/gr14#4]
Use odometrie to finish calibration
(DONE 09.11.16)

**Comment by jeanfrancoisburnier** [comment]
Make calibration available for yellow team

**Comment by AThabuis** [comment]
I know it's quite the detail but that would be great to put the robot at the limit of its base to have some cm in advance compared to its opponent

**Comment by jeanfrancoisburnier** [comment]
Ok @AdrienThabuis I will do it, just for your beautiful eyes
